name: native_auth
description: this package is to implement faceID, touchID and fingerprint authentication
version: 1.0.3
homepage: https://github.com/welitonsousa/native_auth
repository: https://github.com/welitonsousa/native_auth
issue_tracker: https://github.com/welitonsousa/native_auth/issues


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  local_auth: ^1.1.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
