name: native_auth
description: this package is to implement faceID, touchID and fingerprint authentication
version: 1.0.4
homepage: https://github.com/welitonsousa/native_auth
repository: https://github.com/welitonsousa/native_auth
issue_tracker: https://github.com/welitonsousa/native_auth/issues


environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  local_auth: ^2.1.6
  
  flutter:
    sdk: flutter
  local_auth_ios: ^1.1.1
  local_auth_android: ^1.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
